# Natural Language Processing Toolkit 

In [18]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import nltk

NLTK provides Corpus - Provide Lot of existing dataset to process natural Language

Corpus - means a large collection of text
In downloader download all corpora 

In [22]:
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------


Downloader>  q


True

In [23]:
from nltk.corpus import brown
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [24]:
brown?

Type:           CategorizedTaggedCorpusReader
String form:    <CategorizedTaggedCorpusReader in '/usr/share/nltk_data/corpora/brown'>
File:           /opt/conda/lib/python3.7/site-packages/nltk/corpus/reader/tagged.py
Docstring:     
A reader for part-of-speech tagged corpora whose documents are
divided into categories based on their file identifiers.
Init docstring:
Initialize the corpus reader.  Categorization arguments
(``cat_pattern``, ``cat_map``, and ``cat_file``) are passed to
the ``CategorizedCorpusReader`` constructor.  The remaining arguments
are passed to the ``TaggedCorpusReader``.


In [25]:
x=brown.categories()
print(x)
print(len(x))


['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [26]:
#sentences in brown dataset by **sents** of category fiction
data=brown.sents(categories='fiction')

In [27]:
print(data)

[['Thirty-three'], ['Scotty', 'did', 'not', 'go', 'back', 'to', 'school', '.'], ...]


In [28]:
data[1]

['Scotty', 'did', 'not', 'go', 'back', 'to', 'school', '.']

In [29]:
' '.join(data[1]) #join 1st sentence list separated with space

'Scotty did not go back to school .'

# Bag of Words Pipelie
- Get the data/Corpus    #data means real life dataset and corpus is nltk dataset
- Tokenisation , stopword removal
- Stemming
- Building a vocab
- Vectorization
- Classification
- .......................................
- Text-> numbers -> classifiers -> predictions/op
- Tokenisation - document->sentences->words

Here We create a vocab of words for the purpose of vectorization of sentences/documents. each unique word in sentences have some index/no mapped to it which is used in vector of words instead of putting that word in vector of words 
 "[ ['i','like','to','play'.'cricket']....[] ]   we   use   [ [1,5,8,3,2].....[] ]"

## Tokenization & Stopwords Removal 

In [30]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [31]:
document="""It was very pleasant day. the weather was very cool and there were light showers. 
I went to the market to buy some fruits"""

sentence="send all 50 documents related to chapters 1,2,3 at prateek@cb.com"

In [32]:
sents=sent_tokenize(document)
print(sents)

['It was very pleasant day.', 'the weather was very cool and there were light showers.', 'I went to the market to buy some fruits']


In [33]:
sents[0]

'It was very pleasant day.'

In [34]:
words=word_tokenize(document)
print(words)

['It', 'was', 'very', 'pleasant', 'day', '.', 'the', 'weather', 'was', 'very', 'cool', 'and', 'there', 'were', 'light', 'showers', '.', 'I', 'went', 'to', 'the', 'market', 'to', 'buy', 'some', 'fruits']


In [35]:
sentence.split()

['send',
 'all',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'prateek@cb.com']

In [36]:
words=word_tokenize(sentence)
print(words)

['send', 'all', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'prateek', '@', 'cb.com']


so we can see here that it also separates along special characters like @

### Stopwords

In [37]:
from nltk.corpus import stopwords

In [38]:
sw=set(stopwords.words('english'))

In [39]:
print(sw)

{'of', 'mightn', "didn't", "shan't", 'your', 'itself', 's', 'his', 'whom', 'at', 'off', 'their', 'theirs', 'doesn', "don't", 'we', 'both', 'weren', 'hasn', 'mustn', 'more', 'll', 'hers', "aren't", "it's", 'was', "couldn't", 'as', 'wasn', "wouldn't", 'being', 're', 'which', 'hadn', "weren't", "you'd", 'an', 'these', 'with', 'below', 'against', 'it', 'any', 'no', 'm', 'very', 'who', 'from', 'but', 'having', 'into', 'its', 'just', 'when', 'between', 'under', 'me', "you've", 'further', "you'll", 'then', 'again', 'all', 'they', 'same', 'will', 'won', 'has', 'couldn', 'than', 'ourselves', 'over', 'myself', "that'll", 'can', 'does', 'this', 'in', 'been', "hasn't", 'her', 'you', 'here', 'few', "won't", 'after', 'i', "she's", 'he', 'shan', 'not', 'now', 'above', 'down', "needn't", "doesn't", 'are', 'and', 'through', 'most', "shouldn't", "should've", 'until', 'him', 'ours', 'for', 'or', 'because', 'where', 'too', 'on', 'had', "you're", 'other', 'yourselves', 'own', 'yourself', 'doing', 'haven', 

In [40]:
#function to remove stopwords from a text
def remove_stopwords(text,stopwords):
    useful_words=[w for w in text if w not in stopwords]
    return useful_words

In [41]:
text="i am not bothered about her very much"
texts=text.split()    #list of words i.e tokenization
useful_text=remove_stopwords(texts,sw)

In [42]:
print(useful_text)

['bothered', 'much']


In [43]:
'not' in sw

True

Here it also removed 'not' that means it will affect negation in our results. So we have to generate or modify stopwords list according to our need or depending upon use case.

### Tokenization Using Regular Expression

In [44]:
from nltk.tokenize import RegexpTokenizer

In [45]:
tokenizer=RegexpTokenizer('[a-zA-Z@.]+')
useful_text=tokenizer.tokenize(sentence)

In [46]:
print(useful_text)

['send', 'all', 'documents', 'related', 'to', 'chapters', 'at', 'prateek@cb.com']


## Stemming
- Process that transforms partiular words(verbs/plurals) into their radical form
- Preserves the semantics of the sentence without increasing the no of unique tokens
- Ex jums,jumping,jumped,jump ==>>jump

In [47]:
text="""foxes love to make jumps. The quick brown fox was seen jumping over the lovely dog from a 6 feet high wall"""

In [48]:
from nltk.stem.snowball import SnowballStemmer , PorterStemmer
from nltk.stem.lancaster import LancasterStemmer
#nltk provide 3 stemmers  Snowball , Porter , Lancaster Stemmer

In [49]:
ps=PorterStemmer()

In [50]:
ps.stem('lovely')

'love'

In [51]:
ps.stem('loving')

'love'

In [52]:
ps.stem('jumping')

'jump'

In [53]:
ps.stem('jumps')

'jump'

In [54]:
#SnowballStemmer supports multilingual stemmer like french and german
ss=SnowballStemmer('english')

In [55]:
ss.stem('loveingly')

'love'

### Lemmatization
- works almost same as stemming
- difference - stem may not be an actual word whereas, lemma is an actual language word
- WordNet Lemmatizer


see the diff in output of jumping and jumps how lemmatization works

In [56]:
from nltk.stem import WordNetLemmatizer
wn=WordNetLemmatizer()
x=wn.lemmatize('jumps')
print(x)
y=wn.lemmatize('jumping')
print(y)

jump
jumping


### Building Vocab and Vectorization
- Learn how to convert a given sentence into vectors

In [57]:
#sample Corpus contains 4 documents each document can have 1 or more sentences
corpus=['Indian cricket team will wins World Cup says Capt. Virat Kohli. World Cup will be held at Sri Lanka.',
        'We will win next Lok Sabha Elections,says confident Indian PM',
        'The nobel laurate won the hearts of the people.',
        'The movie Raazi is an exciting Indian Spy thriller based upon a real story.'
]

In [58]:
from sklearn.feature_extraction.text import CountVectorizer

In [59]:
cv=CountVectorizer()
vectorized_corpus=cv.fit_transform(corpus)
print(vectorized_corpus)
print(type(vectorized_corpus))

  (0, 12)	1
  (0, 6)	1
  (0, 31)	1
  (0, 37)	2
  (0, 39)	1
  (0, 41)	2
  (0, 7)	2
  (0, 27)	1
  (0, 4)	1
  (0, 35)	1
  (0, 14)	1
  (0, 3)	1
  (0, 11)	1
  (0, 1)	1
  (0, 29)	1
  (0, 15)	1
  (1, 12)	1
  (1, 37)	1
  (1, 27)	1
  (1, 36)	1
  (1, 38)	1
  (1, 19)	1
  (1, 17)	1
  (1, 26)	1
  (1, 8)	1
  (1, 5)	1
  (1, 23)	1
  (2, 32)	3
  (2, 20)	1
  (2, 16)	1
  (2, 40)	1
  (2, 10)	1
  (2, 21)	1
  (2, 22)	1
  (3, 12)	1
  (3, 32)	1
  (3, 18)	1
  (3, 24)	1
  (3, 13)	1
  (3, 0)	1
  (3, 9)	1
  (3, 28)	1
  (3, 33)	1
  (3, 2)	1
  (3, 34)	1
  (3, 25)	1
  (3, 30)	1
<class 'scipy.sparse.csr.csr_matrix'>


we can see it is in sparse matrix form 

In [60]:
#vectorized_corpus?

In [61]:
#vectorized_corpus=vectorized_corpus.tolist()
from scipy.sparse import csr_matrix
vectorized_corpus=vectorized_corpus.toarray()
print(vectorized_corpus)

[[0 1 0 1 1 0 1 2 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1
  0 2 0 1 0 2]
 [0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0
  1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 3 0 0 0
  0 0 0 0 1 0]
 [1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 0
  0 0 0 0 0 0]]


In [62]:
print(vectorized_corpus[0])
len(vectorized_corpus[0])

[0 1 0 1 1 0 1 2 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0
 2 0 1 0 2]


42

vector size is same as no of unique words in vocab i.e 42

In [63]:
print(cv.vocabulary_)
print()
print("size of vocab ",len(cv.vocabulary_.keys()))

{'indian': 12, 'cricket': 6, 'team': 31, 'will': 37, 'wins': 39, 'world': 41, 'cup': 7, 'says': 27, 'capt': 4, 'virat': 35, 'kohli': 14, 'be': 3, 'held': 11, 'at': 1, 'sri': 29, 'lanka': 15, 'we': 36, 'win': 38, 'next': 19, 'lok': 17, 'sabha': 26, 'elections': 8, 'confident': 5, 'pm': 23, 'the': 32, 'nobel': 20, 'laurate': 16, 'won': 40, 'hearts': 10, 'of': 21, 'people': 22, 'movie': 18, 'raazi': 24, 'is': 13, 'an': 0, 'exciting': 9, 'spy': 28, 'thriller': 33, 'based': 2, 'upon': 34, 'real': 25, 'story': 30}

size of vocab  42


Suppose we want to do reverse mapping from a list of no's get the sentence

In [64]:
#reverse mapping
numbers=vectorized_corpus[2]
numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [65]:
s=cv.inverse_transform(numbers)
print(s)

[array(['hearts', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
      dtype='<U9')]


### Vectorization with stopwords Removal

In [66]:
def myTokenizer(document):
    words=tokenizer.tokenize(document.lower())
    words=remove_stopwords(words,sw)
    return words

In [67]:
myTokenizer("This is some Function")

['function']

In [68]:
cv=CountVectorizer(tokenizer=myTokenizer)

In [69]:
from scipy.sparse import csr_matrix
vectorized_corpus=cv.fit_transform(corpus)
print(vectorized_corpus)

  (0, 9)	1
  (0, 3)	1
  (0, 26)	1
  (0, 31)	1
  (0, 32)	2
  (0, 4)	2
  (0, 22)	1
  (0, 1)	1
  (0, 29)	1
  (0, 10)	1
  (0, 8)	1
  (0, 24)	1
  (0, 11)	1
  (1, 9)	1
  (1, 22)	1
  (1, 30)	1
  (1, 15)	1
  (1, 13)	1
  (1, 21)	1
  (1, 5)	1
  (1, 2)	1
  (1, 18)	1
  (2, 16)	1
  (2, 12)	1
  (2, 7)	1
  (2, 17)	1
  (3, 9)	1
  (3, 14)	1
  (3, 19)	1
  (3, 6)	1
  (3, 23)	1
  (3, 27)	1
  (3, 0)	1
  (3, 28)	1
  (3, 20)	1
  (3, 25)	1


In [70]:
from scipy.sparse import csr_matrix
print(type(vectorized_corpus))
#vectorized_corpus=vectorized_corpus.tolist()
vectorized_corpus=vectorized_corpus.toarray()
#print(vectorized_corpus)

<class 'scipy.sparse.csr.csr_matrix'>


In [71]:
print(vectorized_corpus)

[[0 1 0 1 2 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 2]
 [0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0]]


In [72]:
print(len(vectorized_corpus[0]))

33


In [73]:
cv.inverse_transform(vectorized_corpus)

[array(['capt.', 'cricket', 'cup', 'held', 'indian', 'kohli.', 'lanka.',
        'says', 'sri', 'team', 'virat', 'wins', 'world'], dtype='<U9'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U9'),
 array(['hearts', 'laurate', 'nobel', 'people.'], dtype='<U9'),
 array(['based', 'exciting', 'indian', 'movie', 'raazi', 'real', 'spy',
        'story.', 'thriller', 'upon'], dtype='<U9')]

In [74]:
#For test data
test_corpus=['Indian cricket rock!',
]

### For test data don't use fit_transform(vocab size will get shrunk) instead use transform(overwrite same vocab)

In [75]:
cv.transform(test_corpus).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# More Ways to create features
- Unigrams : Every word as a feature
- Bigrams : Two conjuctive word can be treated as a single word
- Tirgrams : 
- n-grams : 
- TF - IDF Normalisation

In [76]:
sent1=["this is good movie"]    #positive review
sent3=["this is good movie but actor was not present"]    #+ve review but based on unigram classified as -ve
sent2=["this is not good movie"] #-ve review

- In unigram each unique word is a feature
- But if we use bigram "not good" is feature "a good" is featre
- We can capture Negation "not" word also

In [77]:
cv=CountVectorizer()

In [78]:
docs=[sent1[0],sent2[0]]
cv.fit_transform(docs).toarray()


array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]])

here in both the array there is 'not' word in 2nd but not in 1st arr 
- we can make ngram when object created CountVectorizer we can sepicfy our own which is by default (1,1)

In [79]:
#bigram
cv=CountVectorizer(ngram_range=(2,2))    #by default(1,1)
docs=[sent1[0],sent2[0]]
cv.fit_transform(docs).toarray()


array([[1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1]])

In [80]:
cv.vocabulary_

{'this is': 4, 'is good': 1, 'good movie': 0, 'is not': 2, 'not good': 3}

In [81]:
#trigram
cv1=CountVectorizer(ngram_range=(3,3))    #by default(1,1)
docs=[sent1[0],sent2[0]]
cv1.fit_transform(docs).toarray()

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]])

In [82]:
cv1.vocabulary_

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

In [83]:
#ngram
cv2=CountVectorizer(ngram_range=(1,3))    #by default(1,1)
docs=[sent1[0],sent2[0]]
cv2.fit_transform(docs).toarray()

array([[1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]])

In [84]:
cv2.vocabulary_
#we can see here vector length also gets increased

{'this': 11,
 'is': 2,
 'good': 0,
 'movie': 7,
 'this is': 12,
 'is good': 3,
 'good movie': 1,
 'this is good': 13,
 'is good movie': 4,
 'not': 8,
 'is not': 5,
 'not good': 9,
 'this is not': 14,
 'is not good': 6,
 'not good movie': 10}

# Tf-idf Normalisation
- Avoid features that occur very often, bcoz they contain very less information
- Information Decreases as the no of occurences increases across different type of document
- So we define another term - "term-document-frequency"(tdf) which associates a weight with every term
- tf . idf is basically product of two terms  
    1. first term  term freq denoted as - tf (t,d) of term t and doc d
    2. second term is - idf (inverse document frq) denoted as - idf (t,d) =  log(N/(1 + Count(t,D) )) 
    where N=no of docs , (D=all docs) and Count(t,D) count of term t across all docs (i.e how many times t appeared                 across all docs) 
    

-  **for term 'good' the value of tf.idf=1*log(3/3) = nearly 0    here less info (wt will be 0 and 1)** 
-  **for term 'not' the value of tf.idf=1*log(3/1) =  heigher wt    means more info**

In [85]:
sent1="this is good movie"
sent2="this was good movie"
sent3="this is not good movie"
corpus=[sent1,sent2,sent3]

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer 

In [87]:
tfidf=TfidfVectorizer()

In [88]:
vc=tfidf.fit_transform(corpus).toarray()
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


**here term 'not' has tf.ifd value=0.61 term 'was' has val=0.69 which is higher**

In [89]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}